# Generated by Django 4.1.7 on 2023-10-23 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('school', models.CharField(default='-', max_length=100)),
                ('major', models.CharField(default='-', max_length=100)),
                ('graduation_year', models.CharField(default=2025, max_length=4)),
                ('annual_income', models.CharField(default='less than 60,000 ₹', max_length=100)),
                ('parent_name', models.CharField(default='-', max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_category', models.CharField(choices=[('Travelling', 'Travelling'), ('Study Material', 'Study Material'), ('Food', 'Food'), ('Miscellaneous', 'Miscellaneous')], default='Travelling', max_length=100)),
                ('transaction_note', models.TextField(default='')),
                ('transaction_history', models.JSONField(default=list)),
                ('transaction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forget_password_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
