# Generated by Django 4.1.7 on 2023-10-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentdata_request_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
