# Generated by Django 4.1.7 on 2023-10-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_moneyrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoneyRequest',
        ),
    ]
